add auth cex account data
KyberNetwork/reserve-data pull request #1127
Opened 2020-10-12 10:30 UTC by NNagato

2020-10-13 07:16 UTC, halink0803 requested changes
There are some lines need to be changed.

2020-10-13 07:16 UTC, halink0803 commented on exchange/binance/binance_endpoint.go
> +	ah                 *authhttp.AuthHTTP
why don't you put this field a meaningful name? `ah` seems do not fine for me.

2020-10-13 07:16 UTC, halink0803 commented on exchange/binance/binance_endpoint.go
> +	respBody, err := ep.ah.DoReq(fmt.Sprintf("%s/api/v3/order/%s", ep.accountDataBaseURL, ep.accountID),
separate lines make it looks clearer.

2020-10-13 07:16 UTC, halink0803 commented on exchange/binance/binance_endpoint.go
> +	respBody, err := ep.ah.DoReq(fmt.Sprintf("%s/wapi/v3/withdrawHistory/%s", ep.accountDataBaseURL, ep.accountID),
same here.

2020-10-13 07:16 UTC, halink0803 commented on lib/auth-http/auth_http.go
> +		fmt.Println(q.Encode())
Is this for debug purpose. Remove it or use logger for it.

2020-10-13 07:16 UTC, halink0803 commented on lib/auth-http/auth_http.go
> +		fmt.Println(req.URL.String())
same here.

2020-10-13 07:32 UTC, halink0803 approved these changes
LGTM

2020-10-16 10:00 UTC, secmask commented
@NNagato how can we turn off auth when we don't want to use it?

2020-10-16 10:30 UTC, NNagato commented
> @NNagato how can we turn off auth when we don't want to use it?

just pass empty access keys and the request will be executed normally

2020-10-21 03:21 UTC, merged