add api return all asset withdraw status
KyberNetwork/reserve-data pull request #1260
Opened 2021-02-18 11:23 UTC by NNagato

2021-02-19 02:15 UTC, secmask requested changes

2021-02-19 02:15 UTC, secmask commented on http/server.go
> +		httputil.ResponseSuccess(c, httputil.WithData(data))
result should be assetID instead of token string.

2021-02-19 04:57 UTC, NNagato commented on http/server.go
> +		httputil.ResponseSuccess(c, httputil.WithData(data))
changed in https://github.com/KyberNetwork/reserve-data/pull/1260/commits/ba0c91a5979f18a9bf3a5cee70628cab6cb56046

2021-02-19 09:48 UTC, secmask commented
looks good, but I would like to take 2 changes
- instead of return a list of asset withdraw status, we return a list of disabled withdraw asset, so any asset that not appear in our list will be assume as enabled to withdraw(in case this API failed somehow, will assume as withdraw allowed)
- update gateway for this API needed?

2021-02-19 11:28 UTC, NNagato commented
> looks good, but I would like to take 2 changes
> 
> * instead of return a list of asset withdraw status, we return a list of disabled withdraw asset, so any asset that not appear in our list will be assume as enabled to withdraw(in case this API failed somehow, will assume as withdraw allowed)
> * update gateway for this API needed?

I made the change in this commit https://github.com/KyberNetwork/reserve-data/pull/1260/commits/7d173782844232b244e59a3dcdc218f610758c66

2021-02-20 02:35 UTC, secmask approved these changes

2021-02-20 02:36 UTC, merged