Use customize id
KyberNetwork/reserve-data pull request #1288
Opened 2021-03-22 15:30 UTC by halink0803

2021-03-22 16:29 UTC, secmask commented on exchange/binance/binance_endpoint.go
> +	withdrawOrderID := fmt.Sprintf("%s_%s", symbol, uuid.New().String())
as they will mostly work the same, using ulid or xid generate nicer unique id string(sortable also shorter)

2021-03-23 02:32 UTC, secmask requested changes

2021-03-23 02:32 UTC, secmask commented on exchange/binance/binance_endpoint.go
> +			"withdrawOrderId": withdrawOrderID,
need to update WithdrawStatus to use this new ID

2021-03-23 03:33 UTC, halink0803 commented on exchange/binance/binance_endpoint.go
> +			"withdrawOrderId": withdrawOrderID,
Yes, I have update WithdrawStatus function with withdrawOrderId as id.

2021-03-23 03:44 UTC, secmask approved these changes

2021-03-23 03:44 UTC, merged