Update binance deposit intermediator
KyberNetwork/reserve-data pull request #1323
Opened 2021-05-05 10:28 UTC by halink0803

2021-05-07 06:51 UTC, secmask requested changes

2021-05-07 06:51 UTC, secmask commented on exchange/binance.go
> +		miningStatus, _, err := bn.binBlockchain.TxStatus(ethereum.HexToHash(txHash))
should assign `txHash = txEntry.Hash` before bellow block can be run correctly.

2021-05-07 06:51 UTC, secmask commented on cmd/migrations/000021_add_binance_intermediate_tx_up.sql
> +CREATE TABLE IF NOT EXISTS "binance_intermediate_tx"(
no need for `IF NOT EXISTS` with migration.

2021-05-07 06:51 UTC, secmask commented on exchange/binance.go
> +	bc, err := binblockchain.NewBlockchain(blockchain, signer, nonce, BinanceOP)
binBlockchain can be init out side and pass into this constructor

2021-05-07 11:09 UTC, halink0803 commented on exchange/binance.go
> +	BSCNetwork             = "BSC"
I use this constant instead of fixed value in other places.

2021-05-07 11:09 UTC, halink0803 commented on exchange/binance.go
> +		if err != nil && err != sql.ErrNoRows {
What should I do with this? I don't know the better approach here.

2021-05-07 11:10 UTC, halink0803 commented on exchange/binance.go
> +		miningStatus, _, err := bn.binBlockchain.TxStatus(ethereum.HexToHash(txHash))
assigned txHash before this block

2021-05-10 04:53 UTC, secmask commented on exchange/binance.go
> +		if err != nil && err != sql.ErrNoRows {
we can define our error const/var, like ErrNotFound

2021-05-10 07:33 UTC, secmask commented on exchange/binance.go
> +	IAmount := common.FloatToBigInt(amount, int64(asset.Decimals))
why caption var name?

2021-05-10 07:33 UTC, secmask commented on exchange/binance.go
> +		return bn.storage.StoreIntermediateDeposit(id, data, false)
how do we use pending state, seem it does not use anywhere.

2021-05-17 09:36 UTC, halink0803 commented
I think the PR is good to go.

2021-05-18 09:51 UTC, secmask approved these changes

2021-05-18 09:52 UTC, merged