add 0x setting
KyberNetwork/reserve-data pull request #1353
Opened 2021-07-13 08:04 UTC by secmask

2021-07-14 10:54 UTC, secmask commented
@ductm54 I added `enabled` field.

2021-07-19 07:38 UTC, NNagato requested changes

2021-07-19 07:38 UTC, NNagato commented on reservesetting/storage/postgres/assets.go
> +		arg.updateZeroXPref = updateZeroXPref{
please check and add this param to `updateMsgs`, cuz, if `updateMsgs` is empty it's, will return an error in line 1194

2021-07-19 09:25 UTC, secmask commented on reservesetting/storage/postgres/assets.go
> +		arg.updateZeroXPref = updateZeroXPref{
nice catch, I fixed it.

2021-07-20 04:20 UTC, NNagato approved these changes
LGTM

2021-08-09 04:38 UTC, merged